//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrpcServer {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MyResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MyResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GrpcServer.MyResource", typeof(MyResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 浙江省宁波市鄞州区姜山镇茅山文山路220号
        ///福建省厦门市海沧区东孚镇东瑶村下尾社山后路51号
        ///浙江省宁波市鄞州区姜山镇茅山文山路220号
        ///上海市上海城区嘉定区兴平路435号
        ///广东省东莞市厚街桥头第三工业区桥南路10号
        ///天津市天津城区西青区经济开发区兴华道26号
        ///浙江省宁波市鄞州区姜山镇茅山文山路220号
        ///上海市上海城区嘉定区兴平路435号
        ///浙江省宁波市鄞州区姜山镇茅山文山路220号
        ///上海市上海城区嘉定区兴平路435号
        ///浙江省宁波市鄞州区姜山镇茅山文山路220号
        ///上海市上海城区嘉定区兴平路435号
        ///广东省东莞市厚街桥头第三工业区桥南路10号
        ///广东省揭阳市普宁市桥北二路西园80幢西起第四间
        ///天津市天津城区西青区经济开发区兴华道26号
        ///陕西省西安市临潼区秦陵街道杨家村刘堡路8号
        ///浙江省宁波市鄞州区姜山镇茅山文山路220号
        ///江苏省苏州市吴菀坪东路209号
        ///浙江省温州市乐清市虹桥镇信达路11号
        ///广东省广州市增城区新塘镇广深大道东145号
        ///河北省秦皇岛市黎昌县工业园区
        ///浙江省温州市乐清市虹桥镇信达路11号
        ///浙江省宁波市鄞州区姜山镇茅山文山路220号
        ///上海市上海城区嘉定区兴平路 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 安安 
        ///安迪
        ///安峰
        ///安凯
        ///安然
        ///安伊
        ///白队
        ///包勇
        ///宝宝
        ///鲍臣
        ///北京
        ///贝贝 
        ///碧容
        ///卜斌
        ///布谷
        ///蔡超
        ///蔡海
        ///蔡琴
        ///蔡生
        ///蔡威
        ///蔡赟
        ///蔡赞
        ///蔡赘
        ///仓管 
        ///仓库
        ///曹民
        ///曹敏
        ///曹生
        ///常聪
        ///常军
        ///常旺
        ///朝恩
        ///车库
        ///辰迹
        ///陈柏
        ///陈彬
        ///陈斌
        ///陈波
        ///陈超
        ///陈朝
        ///陈陈
        ///陈聪
        ///陈飞
        ///陈峰
        ///陈广
        ///陈海
        ///陈豪
        ///陈洪
        ///陈虎
        ///陈华
        ///陈画
        ///陈欢
        ///陈辉
        ///陈杰
        ///陈婕
        ///陈姐
        ///陈静
        ///陈久
        ///陈娟
        ///陈凯
        ///陈克
        ///陈琨
        ///陈浪
        ///陈雷
        ///陈磊
        ///陈利
        ///陈琳
        ///陈龙
        ///陈伦
        ///陈猛
        ///陈敏
        ///陈铭 
        ///陈默
        ///陈培
        ///陈鹏
        ///陈平
        ///陈生
        ///陈涛
        ///陈婷
        ///陈威
        ///陈伟
        ///陈武
        ///陈宪
        ///陈晓
        ///陈岩
        ///陈艳
        ///陈瑶
        ///陈义
        ///陈瑜
        ///陈雨
        ///陈玉
        ///陈周
        ///陈子
        ///陈总
        ///晨曦
        ///成龙
        ///成双
        ///诚易
        ///城外
        ///程斌
        ///程航
        ///程静
        ///程玲
        ///程七
        ///程勇
        ///迟军
        ///楚刚
        ///楚榛
        ///褚斌
        ///褚总
        ///川木
        ///春燕
        ///从丽
        ///崔黎
        ///村长
        ///大货
        ///大鹏
        ///大甜
        ///大颖
        ///戴飞
        ///戴生
        ///戴总
        ///单航
        ///单凯
        ///单民
        ///淡炜
        ///德明
        /// [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string Names {
            get {
                return ResourceManager.GetString("Names", resourceCulture);
            }
        }
    }
}
